# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'yenidagitim.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(803, 399)
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(720, 360, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.tab_bilgialanlari = QtWidgets.QTabWidget(Form)
        self.tab_bilgialanlari.setGeometry(QtCore.QRect(10, 10, 761, 321))
        self.tab_bilgialanlari.setObjectName("tab_bilgialanlari")
        self.bilgialanlari = QtWidgets.QWidget()
        self.bilgialanlari.setObjectName("bilgialanlari")
        self.label = QtWidgets.QLabel(self.bilgialanlari)
        self.label.setGeometry(QtCore.QRect(30, 20, 121, 16))
        self.label.setObjectName("label")
        self.sinav_adi = QtWidgets.QLineEdit(self.bilgialanlari)
        self.sinav_adi.setGeometry(QtCore.QRect(200, 20, 113, 20))
        self.sinav_adi.setObjectName("sinav_adi")
        self.label_2 = QtWidgets.QLabel(self.bilgialanlari)
        self.label_2.setGeometry(QtCore.QRect(30, 70, 161, 16))
        self.label_2.setObjectName("label_2")
        self.sinav_tablosu_01 = QtWidgets.QTableWidget(self.bilgialanlari)
        self.sinav_tablosu_01.setGeometry(QtCore.QRect(340, 70, 401, 211))
        self.sinav_tablosu_01.setObjectName("sinav_tablosu_01")
        self.sinav_tablosu_01.setColumnCount(2)
        self.sinav_tablosu_01.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.sinav_tablosu_01.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.sinav_tablosu_01.setHorizontalHeaderItem(1, item)
        self.sinav_tablosu_01.horizontalHeader().setDefaultSectionSize(200)
        self.label_5 = QtWidgets.QLabel(self.bilgialanlari)
        self.label_5.setGeometry(QtCore.QRect(40, 140, 251, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("QLabel{rgb(255, 0, 0)}")
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setWordWrap(True)
        self.label_5.setObjectName("label_5")
        self.sinav_sayisi = QtWidgets.QSpinBox(self.bilgialanlari)
        self.sinav_sayisi.setGeometry(QtCore.QRect(200, 70, 42, 22))
        self.sinav_sayisi.setMinimum(1)
        self.sinav_sayisi.setObjectName("sinav_sayisi")
        self.tab_bilgialanlari.addTab(self.bilgialanlari, "")
        self.sube_bilgileri = QtWidgets.QWidget()
        self.sube_bilgileri.setObjectName("sube_bilgileri")
        self.sinav_tablosu_02 = QtWidgets.QTableWidget(self.sube_bilgileri)
        self.sinav_tablosu_02.setGeometry(QtCore.QRect(10, 20, 741, 271))
        self.sinav_tablosu_02.setObjectName("sinav_tablosu_02")
        self.sinav_tablosu_02.setColumnCount(1)
        self.sinav_tablosu_02.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.sinav_tablosu_02.setHorizontalHeaderItem(0, item)
        self.label_4 = QtWidgets.QLabel(self.sube_bilgileri)
        self.label_4.setGeometry(QtCore.QRect(290, 0, 171, 16))
        self.label_4.setObjectName("label_4")
        self.tab_bilgialanlari.addTab(self.sube_bilgileri, "")
        self.sinav_yerleri = QtWidgets.QWidget()
        self.sinav_yerleri.setObjectName("sinav_yerleri")
        self.tableWidget_3 = QtWidgets.QTableWidget(self.sinav_yerleri)
        self.tableWidget_3.setGeometry(QtCore.QRect(330, 20, 221, 251))
        self.tableWidget_3.setObjectName("tableWidget_3")
        self.tableWidget_3.setColumnCount(2)
        self.tableWidget_3.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(1, item)
        self.label_3 = QtWidgets.QLabel(self.sinav_yerleri)
        self.label_3.setGeometry(QtCore.QRect(50, 30, 171, 16))
        self.label_3.setObjectName("label_3")
        self.tab_bilgialanlari.addTab(self.sinav_yerleri, "")

        self.retranslateUi(Form)
        self.tab_bilgialanlari.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Yeni Dağıtım"))
        self.pushButton.setText(_translate("Form", "Dağıtımı Yap"))
        self.label.setText(_translate("Form", "Sınav Adı Giriniz"))
        self.label_2.setText(_translate("Form", "Yapılacak Sınav Sayısını Giriniz"))
        item = self.sinav_tablosu_01.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Sınav Sayısı"))
        item = self.sinav_tablosu_01.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Sınav Adı * Mutlaka Doldurun"))
        self.label_5.setText(_translate("Form", "Bilgileri Tam ve Eksiksiz Giriniz"))
        self.tab_bilgialanlari.setTabText(self.tab_bilgialanlari.indexOf(self.bilgialanlari), _translate("Form", "Bilgi Alanlari"))
        item = self.sinav_tablosu_02.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Şube Adı"))
        self.label_4.setText(_translate("Form", "Şubeler İçin Sınav Tercih Ediniz"))
        self.tab_bilgialanlari.setTabText(self.tab_bilgialanlari.indexOf(self.sube_bilgileri), _translate("Form", "Şube Bilgileri"))
        item = self.tableWidget_3.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Salon Adı"))
        item = self.tableWidget_3.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Salon Seçimi"))
        self.label_3.setText(_translate("Form", "Sınav Yapılacak Salonları Seçiniz"))
        self.tab_bilgialanlari.setTabText(self.tab_bilgialanlari.indexOf(self.sinav_yerleri), _translate("Form", "Sınav Yerleri"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

